# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: RaleighAndCo
email: robert@raleighand.co
description: > # this means to ignore newlines until "baseurl:"
  Raleigh &amp; Co. is the home of Robert Raleigh, a serial entrepreneur. RobertRo the Corvallis Youth Garden Project, and was there formation of the Willamette Angel Conference.
url: "http://raleighandco.co" # the base hostname & protocol for your site
baseurl: ''
twitter_username: RaleighAndCo
github_username:  RaleighAndCo
email: hi@raleighand.co
phone: 5035026125

# Build Settings
permalink: 'pretty'
include: ['_pages']
exclude: ['Gemfile', 'node_modules', 'package.json', 'Gruntfile.js', 'README.md']
markdown: kramdown